export const products = [
  {
    id: 1,
    name: "Wireless Mouse",
    category: "Electronics",
    price: 100,
    isAvailable: true,
  },
  {
    id: 2,
    name: "Gaming Keyboard",
    category: "Electronics",
    price: 250,
    isAvailable: false,
  },
  {
    id: 3,
    name: "Running Shoes",
    category: "Footwear",
    price: 180,
    isAvailable: true,
  },
  {
    id: 4,
    name: "Denim Jacket",
    category: "Fashion",
    price: 320,
    isAvailable: true,
  },
  {
    id: 5,
    name: "Coffee Mug",
    category: "Home",
    price: 40,
    isAvailable: false,
  },
  {
    id: 6,
    name: "Bluetooth Speaker",
    category: "Electronics",
    price: 450,
    isAvailable: true,
  },
  {
    id: 7,
    name: "Notebook",
    category: "Stationery",
    price: 30,
    isAvailable: true,
  },
  {
    id: 8,
    name: "Backpack",
    category: "Accessories",
    price: 220,
    isAvailable: false,
  },
  {
    id: 9,
    name: "Water Bottle",
    category: "Sports",
    price: 60,
    isAvailable: true,
  },
  {
    id: 10,
    name: "Smart Watch",
    category: "Electronics",
    price: 800,
    isAvailable: true,
  },
  {
    id: 11,
    name: "Office Chair",
    category: "Furniture",
    price: 950,
    isAvailable: false,
  },
  {
    id: 12,
    name: "LED Lamp",
    category: "Home",
    price: 120,
    isAvailable: true,
  },
  {
    id: 13,
    name: "Sunglasses",
    category: "Accessories",
    price: 150,
    isAvailable: true,
  },
  {
    id: 14,
    name: "Yoga Mat",
    category: "Fitness",
    price: 280,
    isAvailable: false,
  },
  {
    id: 15,
    name: "Headphones",
    category: "Electronics",
    price: 550,
    isAvailable: true,
  },
  {
    id: 16,
    name: "Cookware Set",
    category: "Kitchen",
    price: 700,
    isAvailable: true,
  },
  {
    id: 17,
    name: "T-Shirt",
    category: "Fashion",
    price: 90,
    isAvailable: false,
  },
  {
    id: 18,
    name: "Football",
    category: "Sports",
    price: 110,
    isAvailable: true,
  },
  {
    id: 19,
    name: "Desk Organizer",
    category: "Office",
    price: 75,
    isAvailable: true,
  },
  {
    id: 20,
    name: "Tablet Stand",
    category: "Accessories",
    price: 140,
    isAvailable: false,
  },
];
